### PR TITLE
Kinetic migration

### PR DESCRIPTION
**Pull request by joao-avelino**
Merging kinetic changes with master. They also work in Indigo.

### CODE REVIEW

**Comment by gsaponaro** [comment]
Hi @joao-avelino ! The branch `kinetic-migration` has been merged into `master`, therefore `kinetic-migration` can be probably deleted now. You can do that by going to https://github.com/vislab-tecnico-lisboa/vizzy/pull/63 and clicking 'Delete branch' at the bottom. The advantage is that the repository will be cleaner to maintain, without unneeded branches lying around.

/cc @ruipimentelfigueiredo

**Comment by jsbruglie** [comment]
I was working on this branch, but it was mostly unorganized.
I will **branch out from master**, organize my commits (simplified urdf model for collision, which results in better performance, fixed issues concerned with the migration to Kinetic and others that I have worked on during the past weeks on `model-simplification` branch).

**Comment by gsaponaro** [comment]
Hi @jsbruglie, sure, go ahead in your own branch. In the meantime I have deleted `kinetic-migration`, which has already been merged. I just spoke with @ruipimentelfigueiredo to confirm that.

In general it's a good practice to delete branches that have already been merged, to avoid keeping defunct branches lying around with no novel content. See https://github.com/blog/1335-tidying-up-after-pull-requests

**Comment by joao-avelino** [comment]
Hi @gsaponaro! Thanks for taking a look at it and deleting the branch.

**Comment by ruipimentelfigueiredo** [comment]
Thanks and good job @gsaponaro! You are totally right.

**Pull request merged**
