### PR TITLE
Fixed Vizzy's slippery in simulation. 

### PR DESCRIPTION
**Pull request by joao-avelino**
Fixed Vizzy's slippery in simulation. Replaced old caster wheel with new ones. Active wheels now have single point contacts with the floor. Contacts between all wheels balanced. differential_drive_controller had wrong wheel separation value, which was impacting odometry in simulation.

In 5 runs it always closes the loop perfectly with fake_localization, thus odometry is not accumulating errors. The map is not perfect, though... We can see minor mismatches between the laser and the map along the way, that disappear when the robot returns to the initial point.

### CODE REVIEW

**Comment by joao-avelino** [comment]
@plinioMoreno I believe the we cannot change these parameters (wheel separation) for the real robot. Aren't they part of the segway_rmp driver for each specific segway model we choose to use?

**Comment by plinioMoreno** [comment]
@joao-avelino, yes, you are right. I was thinking that maybe the driver code has somewhere the parameters to compute the odometry and those parameters should match the ones you found.

**Comment by joao-avelino** [comment]
@plinioMoreno Oh, ok. You just got me curious about the driver's value and I did a quick check on the segway driver code. However, it seems turn and forward movement values are computed in the segway it self and simply communicated to the driver: https://github.com/segwayrmp/libsegwayrmp/blob/81f7971630db22babf6c19237f63a26ca5c28b7f/src/segwayrmp.cc#L880

**Comment by plinioMoreno** [comment]
Ok, thanks for checking that @joao-avelino.

**Pull request merged**
